#!/usr/bin/env zsh
set -e

DOTFILES_DIR="$(cd "$(dirname "$0")" && pwd)"
BACKUP_DIR="$HOME/.dotfiles-backup/$(date +%Y-%m-%d-%H%M%S)"

echo "🚀 Rikerizing dotfiles from $DOTFILES_DIR"

# Ensure stow is installed
if ! command -v stow &> /dev/null; then
    echo "Installing stow via Homebrew..."
    brew install stow
fi

# Ensure ~/.config exists (for starship.toml)
mkdir -p "$HOME/.config"

# Ensure ~/.ssh exists as a real directory, so stow links the files inside it
# instead of folding the whole directory into the repo
mkdir -p "$HOME/.ssh" && chmod 700 "$HOME/.ssh"

# A real (non-symlink) ~/.ssh/config is this machine's own hosts. Move it to
# the untracked ~/.ssh/config.local — which the stowed config includes —
# rather than letting stow --adopt overwrite the repo's copy with it.
if [[ -f "$HOME/.ssh/config" && ! -L "$HOME/.ssh/config" ]]; then
    if [[ -e "$HOME/.ssh/config.local" ]]; then
        echo "✗ ~/.ssh/config is a real file but ~/.ssh/config.local already exists." >&2
        echo "  Merge them by hand, then re-run." >&2
        exit 1
    fi
    mv "$HOME/.ssh/config" "$HOME/.ssh/config.local"
    echo "🔐 Moved existing ~/.ssh/config → ~/.ssh/config.local (untracked, still loaded)"
fi

# --- MACHINE PROFILE ---
# Role tags (e.g. "laptop personal") decide which Brewfile.<tag>, shell,
# git, and ssh layers apply here. Untracked; asked once per machine.
source "$DOTFILES_DIR/lib/profile.zsh"
profile_load
echo "🏷  Profile: ${TAGS[*]}"

# --- BACKUP EXISTING DOTFILES ---
# Snapshot every file that stow is about to touch.
# If anything goes wrong, restore from ~/.dotfiles-backup/<timestamp>/

FILES_TO_BACKUP=(
    .zshrc .mix-aliases .mix-exports .mix-path .mix-tags .mix-extra
    .hushlogin .screenrc
    .gitconfig .global-gitignore
    .ssh/config
    .vimrc .gvimrc
    .wgetrc
    .config/starship.toml
    .p10k.zsh
)

echo ""
echo "📦 Backing up existing dotfiles to $BACKUP_DIR"
mkdir -p "$BACKUP_DIR/.config"
mkdir -p "$BACKUP_DIR/.vim"

for file in "${FILES_TO_BACKUP[@]}"; do
    if [[ -e "$HOME/$file" || -L "$HOME/$file" ]]; then
        # Preserve directory structure in backup
        mkdir -p "$BACKUP_DIR/$(dirname "$file")"
        cp -RP "$HOME/$file" "$BACKUP_DIR/$file" 2>/dev/null && \
            echo "  ✓ ~/$file"
    fi
done

# Backup .vim directory if it exists and isn't already a symlink
if [[ -d "$HOME/.vim" && ! -L "$HOME/.vim" ]]; then
    cp -RP "$HOME/.vim" "$BACKUP_DIR/.vim" 2>/dev/null && \
        echo "  ✓ ~/.vim/"
fi

# Backup ~/bin scripts if they exist
if [[ -d "$HOME/bin" && ! -L "$HOME/bin" ]]; then
    cp -RP "$HOME/bin" "$BACKUP_DIR/bin" 2>/dev/null && \
        echo "  ✓ ~/bin/"
fi

echo "  Backup complete."

# --- FIGLET FONTS ---
echo ""
echo "🔤 Installing figlet fonts..."
if command -v figlet &> /dev/null; then
    FIGLET_FONTS_DIR=$(figlet -I 2 2>/dev/null || echo "/opt/homebrew/share/figlet/fonts")
    cp -v "$DOTFILES_DIR"/fonts/*.flf "$FIGLET_FONTS_DIR/" 2>/dev/null && echo "  ✓ figlet fonts installed" || echo "  ⚠ Could not install figlet fonts"
else
    echo "  ⚠ figlet not installed — skipping fonts (run: brew install figlet)"
fi

# --- STOW PACKAGES ---
echo ""
echo "🔗 Symlinking packages..."

PACKAGES=(shell git vim wget bin config ssh)

for pkg in "${PACKAGES[@]}"; do
    echo "  Stowing $pkg..."
    # --adopt moves existing target files INTO the package dir,
    # then stow creates symlinks. Safe for migration from rsync copies.
    stow --adopt -v -d "$DOTFILES_DIR" -t "$HOME" "$pkg" 2>/dev/null || true
    # Re-stow to ensure symlinks are correct
    stow -R -v -d "$DOTFILES_DIR" -t "$HOME" "$pkg"
done

# --- GIT TAG LAYERS ---
# git can't branch on the profile itself, so generate the include list that
# ~/.gitconfig pulls in. Regenerated every run; never committed.
GIT_TAGS_FILE="$(dirname "$DOTFILES_PROFILE")/gitconfig"
echo "# Generated by bootstrap.sh from $DOTFILES_PROFILE — do not edit" > "$GIT_TAGS_FILE"
for tag in "${TAGS[@]}"; do
    if [[ -f "$DOTFILES_DIR/git/.gitconfig.d/$tag" ]]; then
        printf '[include]\n\tpath = ~/.gitconfig.d/%s\n' "$tag" >> "$GIT_TAGS_FILE"
    fi
done

# --- GIT HOOKS ---
echo ""
echo "🪝 Configuring git hooks..."
git -C "$DOTFILES_DIR" config core.hooksPath .githooks
echo "  ✓ .zshrc will be locked (444) after git operations"

# Lock .zshrc to prevent tool auto-injection
chmod 444 "$DOTFILES_DIR/shell/.zshrc" 2>/dev/null
chmod 444 "$HOME/.zshrc" 2>/dev/null

echo ""
echo "✅ All dotfiles symlinked!"
echo ""
echo "Your previous dotfiles are backed up at:"
echo "  $BACKUP_DIR"
echo ""
echo "To restore from backup:"
echo "  cd ~/.dotfiles && stow -D -t ~ shell git vim wget bin config ssh"
echo "  cp -a $BACKUP_DIR/. ~/"
echo ""
echo "Next steps:"
echo "  ./bundle.sh          # Install Homebrew packages for this profile"
echo "  source ~/.zshrc      # Reload shell config"
echo ""
echo "Make it so. 🖖"
